/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _sidebarLayoutRouteImport } from './routes/__sidebarLayout'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as _sidebarLayoutTeacherRouteRouteImport } from './routes/__sidebarLayout/teacher/route'
import { Route as _sidebarLayoutStudentRouteRouteImport } from './routes/__sidebarLayout/student/route'
import { Route as _sidebarLayoutPrincipalRouteRouteImport } from './routes/__sidebarLayout/principal/route'
import { Route as _sidebarLayoutTeacherIndexRouteImport } from './routes/__sidebarLayout/teacher/index'
import { Route as _sidebarLayoutStudentIndexRouteImport } from './routes/__sidebarLayout/student/index'
import { Route as _sidebarLayoutPrincipalIndexRouteImport } from './routes/__sidebarLayout/principal/index'
import { Route as _sidebarLayoutTeacherReportsRouteRouteImport } from './routes/__sidebarLayout/teacher/reports/route'
import { Route as _sidebarLayoutStudentReportsRouteRouteImport } from './routes/__sidebarLayout/student/reports/route'
import { Route as _sidebarLayoutPrincipalStudentsRouteRouteImport } from './routes/__sidebarLayout/principal/students/route'
import { Route as _sidebarLayoutPrincipalPeriodsRouteRouteImport } from './routes/__sidebarLayout/principal/periods/route'
import { Route as _sidebarLayoutPrincipalCoursesRouteRouteImport } from './routes/__sidebarLayout/principal/courses/route'
import { Route as _sidebarLayoutPrincipalClassesRouteRouteImport } from './routes/__sidebarLayout/principal/classes/route'
import { Route as _sidebarLayoutTeacherReportsIndexRouteImport } from './routes/__sidebarLayout/teacher/reports/index'
import { Route as _sidebarLayoutStudentReportsIndexRouteImport } from './routes/__sidebarLayout/student/reports/index'
import { Route as _sidebarLayoutPrincipalStudentsIndexRouteImport } from './routes/__sidebarLayout/principal/students/index'
import { Route as _sidebarLayoutPrincipalPeriodsIndexRouteImport } from './routes/__sidebarLayout/principal/periods/index'
import { Route as _sidebarLayoutPrincipalCoursesIndexRouteImport } from './routes/__sidebarLayout/principal/courses/index'
import { Route as _sidebarLayoutPrincipalClassesIndexRouteImport } from './routes/__sidebarLayout/principal/classes/index'
import { Route as _sidebarLayoutPrincipalStudentsCreateRouteImport } from './routes/__sidebarLayout/principal/students/create'
import { Route as _sidebarLayoutPrincipalPeriodsCreateRouteImport } from './routes/__sidebarLayout/principal/periods/create'
import { Route as _sidebarLayoutPrincipalCoursesCreateRouteImport } from './routes/__sidebarLayout/principal/courses/create'
import { Route as _sidebarLayoutPrincipalClassesCreateRouteImport } from './routes/__sidebarLayout/principal/classes/create'
import { Route as _sidebarLayoutPrincipalStudentsStudentIdEditRouteImport } from './routes/__sidebarLayout/principal/students/$studentId/edit'
import { Route as _sidebarLayoutPrincipalPeriodsPeriodIdEditRouteImport } from './routes/__sidebarLayout/principal/periods/$periodId/edit'
import { Route as _sidebarLayoutPrincipalCoursesCourseIdEditRouteImport } from './routes/__sidebarLayout/principal/courses/$courseId/edit'
import { Route as _sidebarLayoutPrincipalClassesClassIdEditRouteImport } from './routes/__sidebarLayout/principal/classes/$classId/edit'

const _sidebarLayoutRoute = _sidebarLayoutRouteImport.update({
  id: '/__sidebarLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const _sidebarLayoutTeacherRouteRoute =
  _sidebarLayoutTeacherRouteRouteImport.update({
    id: '/teacher',
    path: '/teacher',
    getParentRoute: () => _sidebarLayoutRoute,
  } as any)
const _sidebarLayoutStudentRouteRoute =
  _sidebarLayoutStudentRouteRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => _sidebarLayoutRoute,
  } as any)
const _sidebarLayoutPrincipalRouteRoute =
  _sidebarLayoutPrincipalRouteRouteImport.update({
    id: '/principal',
    path: '/principal',
    getParentRoute: () => _sidebarLayoutRoute,
  } as any)
const _sidebarLayoutTeacherIndexRoute =
  _sidebarLayoutTeacherIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutTeacherRouteRoute,
  } as any)
const _sidebarLayoutStudentIndexRoute =
  _sidebarLayoutStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutStudentRouteRoute,
  } as any)
const _sidebarLayoutPrincipalIndexRoute =
  _sidebarLayoutPrincipalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutPrincipalRouteRoute,
  } as any)
const _sidebarLayoutTeacherReportsRouteRoute =
  _sidebarLayoutTeacherReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => _sidebarLayoutTeacherRouteRoute,
  } as any)
const _sidebarLayoutStudentReportsRouteRoute =
  _sidebarLayoutStudentReportsRouteRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => _sidebarLayoutStudentRouteRoute,
  } as any)
const _sidebarLayoutPrincipalStudentsRouteRoute =
  _sidebarLayoutPrincipalStudentsRouteRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => _sidebarLayoutPrincipalRouteRoute,
  } as any)
const _sidebarLayoutPrincipalPeriodsRouteRoute =
  _sidebarLayoutPrincipalPeriodsRouteRouteImport.update({
    id: '/periods',
    path: '/periods',
    getParentRoute: () => _sidebarLayoutPrincipalRouteRoute,
  } as any)
const _sidebarLayoutPrincipalCoursesRouteRoute =
  _sidebarLayoutPrincipalCoursesRouteRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => _sidebarLayoutPrincipalRouteRoute,
  } as any)
const _sidebarLayoutPrincipalClassesRouteRoute =
  _sidebarLayoutPrincipalClassesRouteRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => _sidebarLayoutPrincipalRouteRoute,
  } as any)
const _sidebarLayoutTeacherReportsIndexRoute =
  _sidebarLayoutTeacherReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutTeacherReportsRouteRoute,
  } as any)
const _sidebarLayoutStudentReportsIndexRoute =
  _sidebarLayoutStudentReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutStudentReportsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalStudentsIndexRoute =
  _sidebarLayoutPrincipalStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutPrincipalStudentsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalPeriodsIndexRoute =
  _sidebarLayoutPrincipalPeriodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutPrincipalPeriodsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalCoursesIndexRoute =
  _sidebarLayoutPrincipalCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutPrincipalCoursesRouteRoute,
  } as any)
const _sidebarLayoutPrincipalClassesIndexRoute =
  _sidebarLayoutPrincipalClassesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutPrincipalClassesRouteRoute,
  } as any)
const _sidebarLayoutPrincipalStudentsCreateRoute =
  _sidebarLayoutPrincipalStudentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => _sidebarLayoutPrincipalStudentsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalPeriodsCreateRoute =
  _sidebarLayoutPrincipalPeriodsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => _sidebarLayoutPrincipalPeriodsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalCoursesCreateRoute =
  _sidebarLayoutPrincipalCoursesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => _sidebarLayoutPrincipalCoursesRouteRoute,
  } as any)
const _sidebarLayoutPrincipalClassesCreateRoute =
  _sidebarLayoutPrincipalClassesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => _sidebarLayoutPrincipalClassesRouteRoute,
  } as any)
const _sidebarLayoutPrincipalStudentsStudentIdEditRoute =
  _sidebarLayoutPrincipalStudentsStudentIdEditRouteImport.update({
    id: '/$studentId/edit',
    path: '/$studentId/edit',
    getParentRoute: () => _sidebarLayoutPrincipalStudentsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute =
  _sidebarLayoutPrincipalPeriodsPeriodIdEditRouteImport.update({
    id: '/$periodId/edit',
    path: '/$periodId/edit',
    getParentRoute: () => _sidebarLayoutPrincipalPeriodsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalCoursesCourseIdEditRoute =
  _sidebarLayoutPrincipalCoursesCourseIdEditRouteImport.update({
    id: '/$courseId/edit',
    path: '/$courseId/edit',
    getParentRoute: () => _sidebarLayoutPrincipalCoursesRouteRoute,
  } as any)
const _sidebarLayoutPrincipalClassesClassIdEditRoute =
  _sidebarLayoutPrincipalClassesClassIdEditRouteImport.update({
    id: '/$classId/edit',
    path: '/$classId/edit',
    getParentRoute: () => _sidebarLayoutPrincipalClassesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/principal': typeof _sidebarLayoutPrincipalRouteRouteWithChildren
  '/student': typeof _sidebarLayoutStudentRouteRouteWithChildren
  '/teacher': typeof _sidebarLayoutTeacherRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/principal/classes': typeof _sidebarLayoutPrincipalClassesRouteRouteWithChildren
  '/principal/courses': typeof _sidebarLayoutPrincipalCoursesRouteRouteWithChildren
  '/principal/periods': typeof _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren
  '/principal/students': typeof _sidebarLayoutPrincipalStudentsRouteRouteWithChildren
  '/student/reports': typeof _sidebarLayoutStudentReportsRouteRouteWithChildren
  '/teacher/reports': typeof _sidebarLayoutTeacherReportsRouteRouteWithChildren
  '/principal/': typeof _sidebarLayoutPrincipalIndexRoute
  '/student/': typeof _sidebarLayoutStudentIndexRoute
  '/teacher/': typeof _sidebarLayoutTeacherIndexRoute
  '/principal/classes/create': typeof _sidebarLayoutPrincipalClassesCreateRoute
  '/principal/courses/create': typeof _sidebarLayoutPrincipalCoursesCreateRoute
  '/principal/periods/create': typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  '/principal/students/create': typeof _sidebarLayoutPrincipalStudentsCreateRoute
  '/principal/classes/': typeof _sidebarLayoutPrincipalClassesIndexRoute
  '/principal/courses/': typeof _sidebarLayoutPrincipalCoursesIndexRoute
  '/principal/periods/': typeof _sidebarLayoutPrincipalPeriodsIndexRoute
  '/principal/students/': typeof _sidebarLayoutPrincipalStudentsIndexRoute
  '/student/reports/': typeof _sidebarLayoutStudentReportsIndexRoute
  '/teacher/reports/': typeof _sidebarLayoutTeacherReportsIndexRoute
  '/principal/classes/$classId/edit': typeof _sidebarLayoutPrincipalClassesClassIdEditRoute
  '/principal/courses/$courseId/edit': typeof _sidebarLayoutPrincipalCoursesCourseIdEditRoute
  '/principal/periods/$periodId/edit': typeof _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute
  '/principal/students/$studentId/edit': typeof _sidebarLayoutPrincipalStudentsStudentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/principal': typeof _sidebarLayoutPrincipalIndexRoute
  '/student': typeof _sidebarLayoutStudentIndexRoute
  '/teacher': typeof _sidebarLayoutTeacherIndexRoute
  '/principal/classes/create': typeof _sidebarLayoutPrincipalClassesCreateRoute
  '/principal/courses/create': typeof _sidebarLayoutPrincipalCoursesCreateRoute
  '/principal/periods/create': typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  '/principal/students/create': typeof _sidebarLayoutPrincipalStudentsCreateRoute
  '/principal/classes': typeof _sidebarLayoutPrincipalClassesIndexRoute
  '/principal/courses': typeof _sidebarLayoutPrincipalCoursesIndexRoute
  '/principal/periods': typeof _sidebarLayoutPrincipalPeriodsIndexRoute
  '/principal/students': typeof _sidebarLayoutPrincipalStudentsIndexRoute
  '/student/reports': typeof _sidebarLayoutStudentReportsIndexRoute
  '/teacher/reports': typeof _sidebarLayoutTeacherReportsIndexRoute
  '/principal/classes/$classId/edit': typeof _sidebarLayoutPrincipalClassesClassIdEditRoute
  '/principal/courses/$courseId/edit': typeof _sidebarLayoutPrincipalCoursesCourseIdEditRoute
  '/principal/periods/$periodId/edit': typeof _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute
  '/principal/students/$studentId/edit': typeof _sidebarLayoutPrincipalStudentsStudentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/__sidebarLayout': typeof _sidebarLayoutRouteWithChildren
  '/__sidebarLayout/principal': typeof _sidebarLayoutPrincipalRouteRouteWithChildren
  '/__sidebarLayout/student': typeof _sidebarLayoutStudentRouteRouteWithChildren
  '/__sidebarLayout/teacher': typeof _sidebarLayoutTeacherRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/__sidebarLayout/principal/classes': typeof _sidebarLayoutPrincipalClassesRouteRouteWithChildren
  '/__sidebarLayout/principal/courses': typeof _sidebarLayoutPrincipalCoursesRouteRouteWithChildren
  '/__sidebarLayout/principal/periods': typeof _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren
  '/__sidebarLayout/principal/students': typeof _sidebarLayoutPrincipalStudentsRouteRouteWithChildren
  '/__sidebarLayout/student/reports': typeof _sidebarLayoutStudentReportsRouteRouteWithChildren
  '/__sidebarLayout/teacher/reports': typeof _sidebarLayoutTeacherReportsRouteRouteWithChildren
  '/__sidebarLayout/principal/': typeof _sidebarLayoutPrincipalIndexRoute
  '/__sidebarLayout/student/': typeof _sidebarLayoutStudentIndexRoute
  '/__sidebarLayout/teacher/': typeof _sidebarLayoutTeacherIndexRoute
  '/__sidebarLayout/principal/classes/create': typeof _sidebarLayoutPrincipalClassesCreateRoute
  '/__sidebarLayout/principal/courses/create': typeof _sidebarLayoutPrincipalCoursesCreateRoute
  '/__sidebarLayout/principal/periods/create': typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  '/__sidebarLayout/principal/students/create': typeof _sidebarLayoutPrincipalStudentsCreateRoute
  '/__sidebarLayout/principal/classes/': typeof _sidebarLayoutPrincipalClassesIndexRoute
  '/__sidebarLayout/principal/courses/': typeof _sidebarLayoutPrincipalCoursesIndexRoute
  '/__sidebarLayout/principal/periods/': typeof _sidebarLayoutPrincipalPeriodsIndexRoute
  '/__sidebarLayout/principal/students/': typeof _sidebarLayoutPrincipalStudentsIndexRoute
  '/__sidebarLayout/student/reports/': typeof _sidebarLayoutStudentReportsIndexRoute
  '/__sidebarLayout/teacher/reports/': typeof _sidebarLayoutTeacherReportsIndexRoute
  '/__sidebarLayout/principal/classes/$classId/edit': typeof _sidebarLayoutPrincipalClassesClassIdEditRoute
  '/__sidebarLayout/principal/courses/$courseId/edit': typeof _sidebarLayoutPrincipalCoursesCourseIdEditRoute
  '/__sidebarLayout/principal/periods/$periodId/edit': typeof _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute
  '/__sidebarLayout/principal/students/$studentId/edit': typeof _sidebarLayoutPrincipalStudentsStudentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/principal'
    | '/student'
    | '/teacher'
    | '/auth/login'
    | '/principal/classes'
    | '/principal/courses'
    | '/principal/periods'
    | '/principal/students'
    | '/student/reports'
    | '/teacher/reports'
    | '/principal/'
    | '/student/'
    | '/teacher/'
    | '/principal/classes/create'
    | '/principal/courses/create'
    | '/principal/periods/create'
    | '/principal/students/create'
    | '/principal/classes/'
    | '/principal/courses/'
    | '/principal/periods/'
    | '/principal/students/'
    | '/student/reports/'
    | '/teacher/reports/'
    | '/principal/classes/$classId/edit'
    | '/principal/courses/$courseId/edit'
    | '/principal/periods/$periodId/edit'
    | '/principal/students/$studentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/principal'
    | '/student'
    | '/teacher'
    | '/principal/classes/create'
    | '/principal/courses/create'
    | '/principal/periods/create'
    | '/principal/students/create'
    | '/principal/classes'
    | '/principal/courses'
    | '/principal/periods'
    | '/principal/students'
    | '/student/reports'
    | '/teacher/reports'
    | '/principal/classes/$classId/edit'
    | '/principal/courses/$courseId/edit'
    | '/principal/periods/$periodId/edit'
    | '/principal/students/$studentId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/__sidebarLayout'
    | '/__sidebarLayout/principal'
    | '/__sidebarLayout/student'
    | '/__sidebarLayout/teacher'
    | '/auth/login'
    | '/__sidebarLayout/principal/classes'
    | '/__sidebarLayout/principal/courses'
    | '/__sidebarLayout/principal/periods'
    | '/__sidebarLayout/principal/students'
    | '/__sidebarLayout/student/reports'
    | '/__sidebarLayout/teacher/reports'
    | '/__sidebarLayout/principal/'
    | '/__sidebarLayout/student/'
    | '/__sidebarLayout/teacher/'
    | '/__sidebarLayout/principal/classes/create'
    | '/__sidebarLayout/principal/courses/create'
    | '/__sidebarLayout/principal/periods/create'
    | '/__sidebarLayout/principal/students/create'
    | '/__sidebarLayout/principal/classes/'
    | '/__sidebarLayout/principal/courses/'
    | '/__sidebarLayout/principal/periods/'
    | '/__sidebarLayout/principal/students/'
    | '/__sidebarLayout/student/reports/'
    | '/__sidebarLayout/teacher/reports/'
    | '/__sidebarLayout/principal/classes/$classId/edit'
    | '/__sidebarLayout/principal/courses/$courseId/edit'
    | '/__sidebarLayout/principal/periods/$periodId/edit'
    | '/__sidebarLayout/principal/students/$studentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  _sidebarLayoutRoute: typeof _sidebarLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__sidebarLayout': {
      id: '/__sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _sidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/__sidebarLayout/teacher': {
      id: '/__sidebarLayout/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof _sidebarLayoutTeacherRouteRouteImport
      parentRoute: typeof _sidebarLayoutRoute
    }
    '/__sidebarLayout/student': {
      id: '/__sidebarLayout/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof _sidebarLayoutStudentRouteRouteImport
      parentRoute: typeof _sidebarLayoutRoute
    }
    '/__sidebarLayout/principal': {
      id: '/__sidebarLayout/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof _sidebarLayoutPrincipalRouteRouteImport
      parentRoute: typeof _sidebarLayoutRoute
    }
    '/__sidebarLayout/teacher/': {
      id: '/__sidebarLayout/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof _sidebarLayoutTeacherIndexRouteImport
      parentRoute: typeof _sidebarLayoutTeacherRouteRoute
    }
    '/__sidebarLayout/student/': {
      id: '/__sidebarLayout/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof _sidebarLayoutStudentIndexRouteImport
      parentRoute: typeof _sidebarLayoutStudentRouteRoute
    }
    '/__sidebarLayout/principal/': {
      id: '/__sidebarLayout/principal/'
      path: '/'
      fullPath: '/principal/'
      preLoaderRoute: typeof _sidebarLayoutPrincipalIndexRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalRouteRoute
    }
    '/__sidebarLayout/teacher/reports': {
      id: '/__sidebarLayout/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof _sidebarLayoutTeacherReportsRouteRouteImport
      parentRoute: typeof _sidebarLayoutTeacherRouteRoute
    }
    '/__sidebarLayout/student/reports': {
      id: '/__sidebarLayout/student/reports'
      path: '/reports'
      fullPath: '/student/reports'
      preLoaderRoute: typeof _sidebarLayoutStudentReportsRouteRouteImport
      parentRoute: typeof _sidebarLayoutStudentRouteRoute
    }
    '/__sidebarLayout/principal/students': {
      id: '/__sidebarLayout/principal/students'
      path: '/students'
      fullPath: '/principal/students'
      preLoaderRoute: typeof _sidebarLayoutPrincipalStudentsRouteRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalRouteRoute
    }
    '/__sidebarLayout/principal/periods': {
      id: '/__sidebarLayout/principal/periods'
      path: '/periods'
      fullPath: '/principal/periods'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalRouteRoute
    }
    '/__sidebarLayout/principal/courses': {
      id: '/__sidebarLayout/principal/courses'
      path: '/courses'
      fullPath: '/principal/courses'
      preLoaderRoute: typeof _sidebarLayoutPrincipalCoursesRouteRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalRouteRoute
    }
    '/__sidebarLayout/principal/classes': {
      id: '/__sidebarLayout/principal/classes'
      path: '/classes'
      fullPath: '/principal/classes'
      preLoaderRoute: typeof _sidebarLayoutPrincipalClassesRouteRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalRouteRoute
    }
    '/__sidebarLayout/teacher/reports/': {
      id: '/__sidebarLayout/teacher/reports/'
      path: '/'
      fullPath: '/teacher/reports/'
      preLoaderRoute: typeof _sidebarLayoutTeacherReportsIndexRouteImport
      parentRoute: typeof _sidebarLayoutTeacherReportsRouteRoute
    }
    '/__sidebarLayout/student/reports/': {
      id: '/__sidebarLayout/student/reports/'
      path: '/'
      fullPath: '/student/reports/'
      preLoaderRoute: typeof _sidebarLayoutStudentReportsIndexRouteImport
      parentRoute: typeof _sidebarLayoutStudentReportsRouteRoute
    }
    '/__sidebarLayout/principal/students/': {
      id: '/__sidebarLayout/principal/students/'
      path: '/'
      fullPath: '/principal/students/'
      preLoaderRoute: typeof _sidebarLayoutPrincipalStudentsIndexRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalStudentsRouteRoute
    }
    '/__sidebarLayout/principal/periods/': {
      id: '/__sidebarLayout/principal/periods/'
      path: '/'
      fullPath: '/principal/periods/'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsIndexRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRoute
    }
    '/__sidebarLayout/principal/courses/': {
      id: '/__sidebarLayout/principal/courses/'
      path: '/'
      fullPath: '/principal/courses/'
      preLoaderRoute: typeof _sidebarLayoutPrincipalCoursesIndexRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalCoursesRouteRoute
    }
    '/__sidebarLayout/principal/classes/': {
      id: '/__sidebarLayout/principal/classes/'
      path: '/'
      fullPath: '/principal/classes/'
      preLoaderRoute: typeof _sidebarLayoutPrincipalClassesIndexRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalClassesRouteRoute
    }
    '/__sidebarLayout/principal/students/create': {
      id: '/__sidebarLayout/principal/students/create'
      path: '/create'
      fullPath: '/principal/students/create'
      preLoaderRoute: typeof _sidebarLayoutPrincipalStudentsCreateRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalStudentsRouteRoute
    }
    '/__sidebarLayout/principal/periods/create': {
      id: '/__sidebarLayout/principal/periods/create'
      path: '/create'
      fullPath: '/principal/periods/create'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsCreateRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRoute
    }
    '/__sidebarLayout/principal/courses/create': {
      id: '/__sidebarLayout/principal/courses/create'
      path: '/create'
      fullPath: '/principal/courses/create'
      preLoaderRoute: typeof _sidebarLayoutPrincipalCoursesCreateRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalCoursesRouteRoute
    }
    '/__sidebarLayout/principal/classes/create': {
      id: '/__sidebarLayout/principal/classes/create'
      path: '/create'
      fullPath: '/principal/classes/create'
      preLoaderRoute: typeof _sidebarLayoutPrincipalClassesCreateRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalClassesRouteRoute
    }
    '/__sidebarLayout/principal/students/$studentId/edit': {
      id: '/__sidebarLayout/principal/students/$studentId/edit'
      path: '/$studentId/edit'
      fullPath: '/principal/students/$studentId/edit'
      preLoaderRoute: typeof _sidebarLayoutPrincipalStudentsStudentIdEditRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalStudentsRouteRoute
    }
    '/__sidebarLayout/principal/periods/$periodId/edit': {
      id: '/__sidebarLayout/principal/periods/$periodId/edit'
      path: '/$periodId/edit'
      fullPath: '/principal/periods/$periodId/edit'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsPeriodIdEditRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRoute
    }
    '/__sidebarLayout/principal/courses/$courseId/edit': {
      id: '/__sidebarLayout/principal/courses/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/principal/courses/$courseId/edit'
      preLoaderRoute: typeof _sidebarLayoutPrincipalCoursesCourseIdEditRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalCoursesRouteRoute
    }
    '/__sidebarLayout/principal/classes/$classId/edit': {
      id: '/__sidebarLayout/principal/classes/$classId/edit'
      path: '/$classId/edit'
      fullPath: '/principal/classes/$classId/edit'
      preLoaderRoute: typeof _sidebarLayoutPrincipalClassesClassIdEditRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalClassesRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface _sidebarLayoutPrincipalClassesRouteRouteChildren {
  _sidebarLayoutPrincipalClassesCreateRoute: typeof _sidebarLayoutPrincipalClassesCreateRoute
  _sidebarLayoutPrincipalClassesIndexRoute: typeof _sidebarLayoutPrincipalClassesIndexRoute
  _sidebarLayoutPrincipalClassesClassIdEditRoute: typeof _sidebarLayoutPrincipalClassesClassIdEditRoute
}

const _sidebarLayoutPrincipalClassesRouteRouteChildren: _sidebarLayoutPrincipalClassesRouteRouteChildren =
  {
    _sidebarLayoutPrincipalClassesCreateRoute:
      _sidebarLayoutPrincipalClassesCreateRoute,
    _sidebarLayoutPrincipalClassesIndexRoute:
      _sidebarLayoutPrincipalClassesIndexRoute,
    _sidebarLayoutPrincipalClassesClassIdEditRoute:
      _sidebarLayoutPrincipalClassesClassIdEditRoute,
  }

const _sidebarLayoutPrincipalClassesRouteRouteWithChildren =
  _sidebarLayoutPrincipalClassesRouteRoute._addFileChildren(
    _sidebarLayoutPrincipalClassesRouteRouteChildren,
  )

interface _sidebarLayoutPrincipalCoursesRouteRouteChildren {
  _sidebarLayoutPrincipalCoursesCreateRoute: typeof _sidebarLayoutPrincipalCoursesCreateRoute
  _sidebarLayoutPrincipalCoursesIndexRoute: typeof _sidebarLayoutPrincipalCoursesIndexRoute
  _sidebarLayoutPrincipalCoursesCourseIdEditRoute: typeof _sidebarLayoutPrincipalCoursesCourseIdEditRoute
}

const _sidebarLayoutPrincipalCoursesRouteRouteChildren: _sidebarLayoutPrincipalCoursesRouteRouteChildren =
  {
    _sidebarLayoutPrincipalCoursesCreateRoute:
      _sidebarLayoutPrincipalCoursesCreateRoute,
    _sidebarLayoutPrincipalCoursesIndexRoute:
      _sidebarLayoutPrincipalCoursesIndexRoute,
    _sidebarLayoutPrincipalCoursesCourseIdEditRoute:
      _sidebarLayoutPrincipalCoursesCourseIdEditRoute,
  }

const _sidebarLayoutPrincipalCoursesRouteRouteWithChildren =
  _sidebarLayoutPrincipalCoursesRouteRoute._addFileChildren(
    _sidebarLayoutPrincipalCoursesRouteRouteChildren,
  )

interface _sidebarLayoutPrincipalPeriodsRouteRouteChildren {
  _sidebarLayoutPrincipalPeriodsCreateRoute: typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  _sidebarLayoutPrincipalPeriodsIndexRoute: typeof _sidebarLayoutPrincipalPeriodsIndexRoute
  _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute: typeof _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute
}

const _sidebarLayoutPrincipalPeriodsRouteRouteChildren: _sidebarLayoutPrincipalPeriodsRouteRouteChildren =
  {
    _sidebarLayoutPrincipalPeriodsCreateRoute:
      _sidebarLayoutPrincipalPeriodsCreateRoute,
    _sidebarLayoutPrincipalPeriodsIndexRoute:
      _sidebarLayoutPrincipalPeriodsIndexRoute,
    _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute:
      _sidebarLayoutPrincipalPeriodsPeriodIdEditRoute,
  }

const _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren =
  _sidebarLayoutPrincipalPeriodsRouteRoute._addFileChildren(
    _sidebarLayoutPrincipalPeriodsRouteRouteChildren,
  )

interface _sidebarLayoutPrincipalStudentsRouteRouteChildren {
  _sidebarLayoutPrincipalStudentsCreateRoute: typeof _sidebarLayoutPrincipalStudentsCreateRoute
  _sidebarLayoutPrincipalStudentsIndexRoute: typeof _sidebarLayoutPrincipalStudentsIndexRoute
  _sidebarLayoutPrincipalStudentsStudentIdEditRoute: typeof _sidebarLayoutPrincipalStudentsStudentIdEditRoute
}

const _sidebarLayoutPrincipalStudentsRouteRouteChildren: _sidebarLayoutPrincipalStudentsRouteRouteChildren =
  {
    _sidebarLayoutPrincipalStudentsCreateRoute:
      _sidebarLayoutPrincipalStudentsCreateRoute,
    _sidebarLayoutPrincipalStudentsIndexRoute:
      _sidebarLayoutPrincipalStudentsIndexRoute,
    _sidebarLayoutPrincipalStudentsStudentIdEditRoute:
      _sidebarLayoutPrincipalStudentsStudentIdEditRoute,
  }

const _sidebarLayoutPrincipalStudentsRouteRouteWithChildren =
  _sidebarLayoutPrincipalStudentsRouteRoute._addFileChildren(
    _sidebarLayoutPrincipalStudentsRouteRouteChildren,
  )

interface _sidebarLayoutPrincipalRouteRouteChildren {
  _sidebarLayoutPrincipalClassesRouteRoute: typeof _sidebarLayoutPrincipalClassesRouteRouteWithChildren
  _sidebarLayoutPrincipalCoursesRouteRoute: typeof _sidebarLayoutPrincipalCoursesRouteRouteWithChildren
  _sidebarLayoutPrincipalPeriodsRouteRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren
  _sidebarLayoutPrincipalStudentsRouteRoute: typeof _sidebarLayoutPrincipalStudentsRouteRouteWithChildren
  _sidebarLayoutPrincipalIndexRoute: typeof _sidebarLayoutPrincipalIndexRoute
}

const _sidebarLayoutPrincipalRouteRouteChildren: _sidebarLayoutPrincipalRouteRouteChildren =
  {
    _sidebarLayoutPrincipalClassesRouteRoute:
      _sidebarLayoutPrincipalClassesRouteRouteWithChildren,
    _sidebarLayoutPrincipalCoursesRouteRoute:
      _sidebarLayoutPrincipalCoursesRouteRouteWithChildren,
    _sidebarLayoutPrincipalPeriodsRouteRoute:
      _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren,
    _sidebarLayoutPrincipalStudentsRouteRoute:
      _sidebarLayoutPrincipalStudentsRouteRouteWithChildren,
    _sidebarLayoutPrincipalIndexRoute: _sidebarLayoutPrincipalIndexRoute,
  }

const _sidebarLayoutPrincipalRouteRouteWithChildren =
  _sidebarLayoutPrincipalRouteRoute._addFileChildren(
    _sidebarLayoutPrincipalRouteRouteChildren,
  )

interface _sidebarLayoutStudentReportsRouteRouteChildren {
  _sidebarLayoutStudentReportsIndexRoute: typeof _sidebarLayoutStudentReportsIndexRoute
}

const _sidebarLayoutStudentReportsRouteRouteChildren: _sidebarLayoutStudentReportsRouteRouteChildren =
  {
    _sidebarLayoutStudentReportsIndexRoute:
      _sidebarLayoutStudentReportsIndexRoute,
  }

const _sidebarLayoutStudentReportsRouteRouteWithChildren =
  _sidebarLayoutStudentReportsRouteRoute._addFileChildren(
    _sidebarLayoutStudentReportsRouteRouteChildren,
  )

interface _sidebarLayoutStudentRouteRouteChildren {
  _sidebarLayoutStudentReportsRouteRoute: typeof _sidebarLayoutStudentReportsRouteRouteWithChildren
  _sidebarLayoutStudentIndexRoute: typeof _sidebarLayoutStudentIndexRoute
}

const _sidebarLayoutStudentRouteRouteChildren: _sidebarLayoutStudentRouteRouteChildren =
  {
    _sidebarLayoutStudentReportsRouteRoute:
      _sidebarLayoutStudentReportsRouteRouteWithChildren,
    _sidebarLayoutStudentIndexRoute: _sidebarLayoutStudentIndexRoute,
  }

const _sidebarLayoutStudentRouteRouteWithChildren =
  _sidebarLayoutStudentRouteRoute._addFileChildren(
    _sidebarLayoutStudentRouteRouteChildren,
  )

interface _sidebarLayoutTeacherReportsRouteRouteChildren {
  _sidebarLayoutTeacherReportsIndexRoute: typeof _sidebarLayoutTeacherReportsIndexRoute
}

const _sidebarLayoutTeacherReportsRouteRouteChildren: _sidebarLayoutTeacherReportsRouteRouteChildren =
  {
    _sidebarLayoutTeacherReportsIndexRoute:
      _sidebarLayoutTeacherReportsIndexRoute,
  }

const _sidebarLayoutTeacherReportsRouteRouteWithChildren =
  _sidebarLayoutTeacherReportsRouteRoute._addFileChildren(
    _sidebarLayoutTeacherReportsRouteRouteChildren,
  )

interface _sidebarLayoutTeacherRouteRouteChildren {
  _sidebarLayoutTeacherReportsRouteRoute: typeof _sidebarLayoutTeacherReportsRouteRouteWithChildren
  _sidebarLayoutTeacherIndexRoute: typeof _sidebarLayoutTeacherIndexRoute
}

const _sidebarLayoutTeacherRouteRouteChildren: _sidebarLayoutTeacherRouteRouteChildren =
  {
    _sidebarLayoutTeacherReportsRouteRoute:
      _sidebarLayoutTeacherReportsRouteRouteWithChildren,
    _sidebarLayoutTeacherIndexRoute: _sidebarLayoutTeacherIndexRoute,
  }

const _sidebarLayoutTeacherRouteRouteWithChildren =
  _sidebarLayoutTeacherRouteRoute._addFileChildren(
    _sidebarLayoutTeacherRouteRouteChildren,
  )

interface _sidebarLayoutRouteChildren {
  _sidebarLayoutPrincipalRouteRoute: typeof _sidebarLayoutPrincipalRouteRouteWithChildren
  _sidebarLayoutStudentRouteRoute: typeof _sidebarLayoutStudentRouteRouteWithChildren
  _sidebarLayoutTeacherRouteRoute: typeof _sidebarLayoutTeacherRouteRouteWithChildren
}

const _sidebarLayoutRouteChildren: _sidebarLayoutRouteChildren = {
  _sidebarLayoutPrincipalRouteRoute:
    _sidebarLayoutPrincipalRouteRouteWithChildren,
  _sidebarLayoutStudentRouteRoute: _sidebarLayoutStudentRouteRouteWithChildren,
  _sidebarLayoutTeacherRouteRoute: _sidebarLayoutTeacherRouteRouteWithChildren,
}

const _sidebarLayoutRouteWithChildren = _sidebarLayoutRoute._addFileChildren(
  _sidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  _sidebarLayoutRoute: _sidebarLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
