/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _sidebarLayoutRouteImport } from './routes/__sidebarLayout'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as _sidebarLayoutPrincipalPeriodsRouteRouteImport } from './routes/__sidebarLayout/principal/periods/route'
import { Route as _sidebarLayoutPrincipalPeriodsIndexRouteImport } from './routes/__sidebarLayout/principal/periods/index'
import { Route as _sidebarLayoutPrincipalPeriodsCreateRouteImport } from './routes/__sidebarLayout/principal/periods/create'

const _sidebarLayoutRoute = _sidebarLayoutRouteImport.update({
  id: '/__sidebarLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const _sidebarLayoutPrincipalPeriodsRouteRoute =
  _sidebarLayoutPrincipalPeriodsRouteRouteImport.update({
    id: '/principal/periods',
    path: '/principal/periods',
    getParentRoute: () => _sidebarLayoutRoute,
  } as any)
const _sidebarLayoutPrincipalPeriodsIndexRoute =
  _sidebarLayoutPrincipalPeriodsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _sidebarLayoutPrincipalPeriodsRouteRoute,
  } as any)
const _sidebarLayoutPrincipalPeriodsCreateRoute =
  _sidebarLayoutPrincipalPeriodsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => _sidebarLayoutPrincipalPeriodsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/principal/periods': typeof _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren
  '/principal/periods/create': typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  '/principal/periods/': typeof _sidebarLayoutPrincipalPeriodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/principal/periods/create': typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  '/principal/periods': typeof _sidebarLayoutPrincipalPeriodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/__sidebarLayout': typeof _sidebarLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/__sidebarLayout/principal/periods': typeof _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren
  '/__sidebarLayout/principal/periods/create': typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  '/__sidebarLayout/principal/periods/': typeof _sidebarLayoutPrincipalPeriodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/principal/periods'
    | '/principal/periods/create'
    | '/principal/periods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/principal/periods/create'
    | '/principal/periods'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/__sidebarLayout'
    | '/auth/login'
    | '/__sidebarLayout/principal/periods'
    | '/__sidebarLayout/principal/periods/create'
    | '/__sidebarLayout/principal/periods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  _sidebarLayoutRoute: typeof _sidebarLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__sidebarLayout': {
      id: '/__sidebarLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _sidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/__sidebarLayout/principal/periods': {
      id: '/__sidebarLayout/principal/periods'
      path: '/principal/periods'
      fullPath: '/principal/periods'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRouteImport
      parentRoute: typeof _sidebarLayoutRoute
    }
    '/__sidebarLayout/principal/periods/': {
      id: '/__sidebarLayout/principal/periods/'
      path: '/'
      fullPath: '/principal/periods/'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsIndexRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRoute
    }
    '/__sidebarLayout/principal/periods/create': {
      id: '/__sidebarLayout/principal/periods/create'
      path: '/create'
      fullPath: '/principal/periods/create'
      preLoaderRoute: typeof _sidebarLayoutPrincipalPeriodsCreateRouteImport
      parentRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface _sidebarLayoutPrincipalPeriodsRouteRouteChildren {
  _sidebarLayoutPrincipalPeriodsCreateRoute: typeof _sidebarLayoutPrincipalPeriodsCreateRoute
  _sidebarLayoutPrincipalPeriodsIndexRoute: typeof _sidebarLayoutPrincipalPeriodsIndexRoute
}

const _sidebarLayoutPrincipalPeriodsRouteRouteChildren: _sidebarLayoutPrincipalPeriodsRouteRouteChildren =
  {
    _sidebarLayoutPrincipalPeriodsCreateRoute:
      _sidebarLayoutPrincipalPeriodsCreateRoute,
    _sidebarLayoutPrincipalPeriodsIndexRoute:
      _sidebarLayoutPrincipalPeriodsIndexRoute,
  }

const _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren =
  _sidebarLayoutPrincipalPeriodsRouteRoute._addFileChildren(
    _sidebarLayoutPrincipalPeriodsRouteRouteChildren,
  )

interface _sidebarLayoutRouteChildren {
  _sidebarLayoutPrincipalPeriodsRouteRoute: typeof _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren
}

const _sidebarLayoutRouteChildren: _sidebarLayoutRouteChildren = {
  _sidebarLayoutPrincipalPeriodsRouteRoute:
    _sidebarLayoutPrincipalPeriodsRouteRouteWithChildren,
}

const _sidebarLayoutRouteWithChildren = _sidebarLayoutRoute._addFileChildren(
  _sidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  _sidebarLayoutRoute: _sidebarLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
